name: "Chaudière TCP Control"
version: "1.0.0"
slug: "chaudiere_tcp"
description: "Add-on pour piloter la chaudière via TCP depuis Home Assistant"
arch:
  - aarch64
  - armv7
  - amd64
startup: application
boot: auto
host_network: true
options: {}
schema: {}
image: "local/chaudiere_tcp"
