name: "Boiler TCP Bridge"
version: "1.2.9"
slug: "boiler_tcp_bridge"
description: "Bridge TCP chaudière vers MQTT pour Home Assistant"
url: "https://github.com/xavier-1971/ha-addons/tree/main/my_boiler_bridge"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
options:
  tcp_host: "192.168.1.16"
  tcp_port: 8899
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
schema:
  tcp_host: "str"
  tcp_port: "int"
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_user: "str"
  mqtt_password: "str"
